export type Project = {
  name: string;
  domains: string[];
  country: string;
  desc: string;
  year: number;
  image: string;
  playStore?: string;
  appStore?: string;
  isPersonalProject?: boolean;
  type: "mobile" | "desktop";
  website?: string;
};

const projects: Project[] = [
  {
    name: "Account & Expense Manager",
    domains: ["Productivity"],
    country: "Worldwide",
    desc: "Easily manage your day-to-day transactions",
    year: 2022,
    image: "/images/projects/account-manager.png",
    playStore: "com.itwaves.geocam",
    appStore: "https://apps.apple.com/in/app/gps-camera-geocam/id6502434797",
    isPersonalProject: true,
    type: "mobile",
  },
  {
    name: "Geo Cam",
    domains: ["Photography"],
    country: "Worldwide",
    desc: "Geo-tags your photos and videos for a complete storytelling experience",
    year: 2024,
    image: "/images/projects/geo-cam.png",
    playStore: "com.itwaves.accountmanager",
    appStore:
      "https://apps.apple.com/us/app/account-expense-manager/id1596113242",
    isPersonalProject: true,
    type: "mobile",
  },
  {
    name: "Keep Links",
    domains: ["Productivity"],
    country: "Worldwide",
    desc: "Your Go-To Solution for Organizing and Accessing Important Links",
    year: 2024,
    image: "/images/projects/keep-links.png",
    playStore: "com.itwaves.keeplinks",
    appStore:
      "https://apps.apple.com/in/app/keeplinks-save-my-links/id6544796456",
    isPersonalProject: true,
    type: "mobile",
  },
  {
    name: "Tagworx Inventory",
    domains: ["Utility"],
    country: "Worldwide",
    desc: "Asset & Inventory Management made easy.",
    year: 2023,
    image: "/images/projects/tagworx.png",
    playStore: "com.tagworx.inventory",
    website: "https://worx.software/",
    type: "mobile",
  },
  {
    name: "UPayments",
    domains: ["Finance"],
    country: "Worldwide",
    desc: "Create online store with built-in payment gateway, shipping & delivery integration, tracking & analytics tools and more.",
    year: 2021,
    image: "/images/projects/upay.png",
    playStore: "com.upay.upayments.mobile",
    appStore: "https://apps.apple.com/kw/app/upayments/id1311356029",
    type: "mobile",
    website: "https://upayments.com/en/",
  },
  {
    name: "Melaleuca Shopping",
    domains: ["Shopping"],
    country: "Worldwide",
    desc: "Ecommerce app for Melaleuca: The Wellness Company",
    year: 2023,
    image: "/images/projects/melaleuca.png",
    playStore: "com.melaleuca.shopping",
    appStore: "https://apps.apple.com/in/app/melaleuca-shopping/id6450118542",
    website: "https://www.melaleuca.com/",
    type: "mobile",
  },
  {
    name: "Baduli Music",
    domains: ["Music"],
    country: "India",
    desc: "Music app",
    year: 2024,
    image: "/images/projects/baduli.png",
    playStore: "com.badulimusicapp",
    appStore: "https://apps.apple.com/us/app/baduli-music/id6739450218",
    type: "mobile",
  },
  {
    name: "OZZI - Global Safety",
    domains: ["Travel & Local", "News"],
    country: "USA",
    desc: "The ultimate AI-powered safety app designed to be your personal guardian, no matter where you are in the world.",
    year: 2024,
    image: "/images/projects/ozzi.png",
    playStore: "com.ozzi.app",
    appStore: "https://apps.apple.com/us/app/ozzi-global-safety/id1626860915",
    website: "https://ozzi.app/",
    type: "mobile",
  },
  {
    name: "Callingly",
    domains: ["Business"],
    country: "Worldwide",
    desc: "Lead followup on steroids.",
    year: 2023,
    image: "/images/projects/callingly.png",
    website: "https://callingly.com/",
    playStore: "com.callingly.callingly",
    appStore: "https://apps.apple.com/ca/app/callingly/id1637683213",
    type: "mobile",
  },
  {
    name: "SML Lens",
    domains: ["Productivity"],
    country: "India",
    desc: "Geotagging app by SML ISUZU",
    year: 2022,
    image: "/images/projects/sml-lens.png",
    playStore: "com.sml.lens",
    appStore: "https://apps.apple.com/us/app/sml-lens/id1658239204",
    type: "mobile",
  },
  {
    name: "Eboard Pro",
    domains: ["Business"],
    country: "India",
    desc: "Lead management app for SML ISUZU",
    year: 2024,
    image: "/images/projects/sml-eboard.png",
    playStore: "com.app.eboardPro",
    appStore: "https://apps.apple.com/us/app/eboard-pro/id6502770470",
    type: "mobile",
  },
  {
    name: "Vahaan Suraksha",
    domains: ["Business"],
    country: "India",
    desc: "Vahan Suraksha is an app designed to enhance vehicle safety and security.",
    year: 2024,
    image: "/images/projects/sml-logistics.png",
    playStore: "com.app.smlLogistics",
    type: "mobile",
  },
  {
    name: "UCIA Sampada",
    domains: ["Utility"],
    country: "India",
    desc: "Sales management app for UCIA",
    year: 2024,
    image: "/images/projects/unicharm.png",
    playStore: "com.unicharm.pos",
    appStore: "https://apps.apple.com/us/app/ucia-sampada/id6738113341",
    type: "mobile",
  },
  {
    name: "I'M IN",
    domains: ["Sports"],
    country: "Kuwait",
    desc: "Feel free to explore sports events happening around you. Meet new players who are close to your level. Seek new challenges amongst your friends. Take on the I'M IN experience, Let's go!",
    year: 2022,
    image: "/images/projects/imin.jpg",
    playStore: "com.goinfoo.imin",
    appStore: "https://apps.apple.com/in/app/im-in/id1562889443",
    type: "mobile",
  },
  {
    name: "Community Voice",
    domains: ["Social"],
    country: "Worldwide",
    desc: "Connecting Communities Through Communication!",
    year: 2022,
    image: "/images/projects/community-voice.png",
    playStore: "com.communityvoice.app",
    appStore: "https://apps.apple.com/us/app/community-voice/id1622145253",
    type: "mobile",
    website: "https://communityvoice.app/",
  },
  {
    name: "The Cancer App",
    desc: "Suport for cancer patients",
    country: "Worldwide",
    domains: ["Health & Fitness"],
    year: 2021,
    image: "/images/projects/screw-cancer.webp",
    playStore: "com.screwcancer.app",
    appStore: "https://apps.apple.com/in/app/the-cancer-app/id1450257601",
    type: "mobile",
    website: "https://www.the-cancer-app.com/",
  },
  {
    name: "Ando Rider",
    desc: "Rider app for Kenya based Food & Beverage delivery company.",
    domains: ["Food & Beverage"],
    country: "Kenya",
    year: 2022,
    image: "/images/projects/ando-foods.png",
    playStore: "com.andofoods.rider",
    type: "mobile",
  },
  {
    name: "People Asset",
    desc: "Thought-provoking knowledge on leadership, business strategy, workplace organization, and human resources.",
    domains: ["Business"],
    country: "Worldwide",
    year: 2020,
    image: "/images/projects/people-asset.png",
    playStore: "com.peopleasset",
    appStore: "https://apps.apple.com/in/app/peopleasset/id1545833242",
    type: "mobile",
    website: "https://www.peopleasset.in/",
  },
  {
    name: "Salonista - Salon Booking App",
    desc: "Professional beauty salon appointment booking and scheduler app",
    domains: ["Food & Beverage"],
    country: "UAE",
    year: 2020,
    image: "/images/projects/salonista.jpg",
    playStore: "com.salonista.android",
    appStore:
      "https://apps.apple.com/us/app/salonista-salon-booking-app/id1521804032",
    type: "mobile",
  },
  {
    name: "eQWe",
    domains: ["Food & Beverage"],
    country: "Worldwide",
    desc: "Find the ideal meeting point for you and your friends!",
    year: 2020,
    image: "/images/projects/eqwe.webp",
    playStore: "com.perfectlocation.eqwe",
    appStore: "https://apps.apple.com/in/app/eqwe/id1527450909",
    type: "mobile",
  },
  {
    name: "Whitehat JR",
    domains: ["Education"],
    country: "Worldwide",
    desc: "WhiteHat Jr: The LIVE Coding, Maths and Music Class Booking App ",
    year: 2021,
    image: "/images/projects/whitehat.webp",
    playStore: "com.whitehatjr",

    type: "mobile",
  },
  {
    name: "ShopSe Digital Finance",
    domains: ["Finance"],
    country: "India",
    desc: "Shop instantly and pay later in easy No Cost EMIs",
    year: 2022,
    image: "/images/projects/shopse.webp",
    playStore: "com.shopse.consumer",
    appStore:
      "https://apps.apple.com/in/app/shopse-shop-now-pay-later/id1501675725",
    type: "mobile",
  },
  {
    name: "ShopSe Merchant",
    domains: ["Finance"],
    country: "India",
    desc: "Shopse merchant app",
    year: 2022,
    image: "/images/projects/shopse-merchant.webp",
    playStore: "com.shopse.merchant",
    appStore:
      "https://apps.apple.com/in/app/shopse-pay-later-for-business/id1501677217",
    type: "mobile",
  },
  {
    name: "ShopSe Sales Support",
    domains: ["Finance"],
    country: "India",
    desc: "Shopse sales support app",
    year: 2022,
    image: "/images/projects/shopse-sales.webp",
    playStore: "com.shopse.sales",
    type: "mobile",
  },
];

export default projects;
